### ISSUE TITLE
Dataset collection

### ISSUE THREAD

**Issue by dhruvabhat24** [Narcoguard/Drug-Traffic-Tracking#5]
## Objective : 
Createa deailed `documentation` on the collected datasets.

- [ ] Collect the datasets of images or videos which are having drug keywords. 
- [ ] if datasets are not available create 5 basic image example datasets and if possible one video dataset. 
- [ ] Clean the data
- [ ] Complete it by september 30 2024

**Comment by GajananShenvi** [comment]
## Objective : 
Createa deailed `documentation` on the collected datasets.

- [X] Collect the datasets of images or videos which are having drug keywords. 
- [X] if datasets are not available create 5 basic image example datasets and if possible one video dataset. 
- [X] Clean the data
- [X] Complete it by september 30 2024
