### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dhruvabhat24** [Narcoguard/Drug-Traffic-Tracking#7]
# Objective : 
Create a `documentation` on the models which are used for audio processing. 

- [ ] Look for the pretrained models
- [ ] Pros and consequences of pretraned model. 
- [ ] Create a `readme.md` file and all the documentation in that.
- [ ] Complete it by september 29th 2024

**Comment by Shivaprada-upadya** [comment]
# Objective : 
Create a `documentation` on the models which are used for audio processing. 

- [X] Look for the pretrained models
- [X] Pros and consequences of pretrained model. 
- [X] Create a `readme.md` file and all the documentation in that.
- [X] Complete it by september 29th 2024
